### ISSUE TITLE
Using the card as part of a horizontal stack breaks the width/height css

### ISSUE THREAD

**Issue by c11umw** [dingausmwald/circle-sensor-card#1]
When using the card as part of a horizontal stack it ignores the  height/width.
When used in a vertical stack it's fine. Just the horizontal that breaks it.

Example of normal solo use:
```yaml
type: custom:circle-sensor-card
entity: sensor.node_proxmox_containers_running
max: 23
min: 0
stroke_width: 5
gradient: true
units: W
show_max: true
show_card: true
fill: rgba(28,28,28,0)
font_style:
  color: "#ccc"
  font-size: 1.0em
stroke_bg_color: "#1F75FE"
color_stops:
  "0": "#bb3333"
  "5": "#FFBF00"
  "11": "#00bb00"
style:
  top: 0%
  left: 0%
  width: 50px
  height: 50px
```
When used as part of a horizontal stack:
```yaml
type: horizontal-stack
cards:
  - type: custom:circle-sensor-card
    entity: sensor.node_proxmox_containers_running
    max: 23
    min: 0
    stroke_width: 5
    gradient: true
    units: W
    show_max: true
    show_card: true
    fill: rgba(28,28,28,0)
    font_style:
      color: "#ccc"
      font-size: 1.0em
    stroke_bg_color: "#1F75FE"
    color_stops:
      "0": "#bb3333"
      "5": "#FFBF00"
      "11": "#00bb00"
    style:
      top: 0%
      left: 0%
      width: 50px
      height: 50px
```
How they compare:

![Image](https://github.com/user-attachments/assets/bd10de0c-2964-4d8f-9fa6-e3e71c3cac4d)

Same results if I swap width/height to:
```
    --circle-sensor-width: 50px
    --circle-sensor-height: 50px
```
